const pizzaHutData = {
    title: "Pizza Hut",
    imageUrl: "https://placehold.co/800x400/e63946/ffffff.png?text=Pizza+Hut",
    logoUrl: "https://placehold.co/200x200/e63946/ffffff.png?text=PH",
    cuisines: ["Pizza", "Italian", "Fast Food", "Desserts"],
    foods: [
        {
            name: "Margherita Pizza",
            description: "Classic delight with 100% real mozzarella cheese",
            price: 219,
            imageUrl: "https://placehold.co/400x300/e63946/ffffff.png?text=Margherita",
            category: "Pizza",
            isVeg: true,
            isAvailable: true,
        },
        {
            name: "Pepperoni Feast",
            description: "Loaded with double pepperoni and extra cheese",
            price: 449,
            imageUrl: "https://placehold.co/400x300/e63946/ffffff.png?text=Pepperoni",
            category: "Pizza",
            isVeg: false,
            isAvailable: true,
        },
        {
            name: "Veggie Supreme Pizza",
            description: "Onion, capsicum, mushroom, tomato, and corn",
            price: 379,
            imageUrl: "https://placehold.co/400x300/e63946/ffffff.png?text=Veggie+Supreme",
            category: "Pizza",
            isVeg: true,
            isAvailable: true,
        },
        {
            name: "Chicken Tikka Pizza",
            description: "Spicy chicken tikka chunks with onions and bell peppers",
            price: 459,
            imageUrl: "https://placehold.co/400x300/e63946/ffffff.png?text=Chicken+Tikka",
            category: "Pizza",
            isVeg: false,
            isAvailable: true,
        },
        {
            name: "Garlic Breadsticks",
            description: "Soft breadsticks brushed with garlic butter",
            price: 149,
            imageUrl: "https://placehold.co/400x300/f4a261/ffffff.png?text=Garlic+Bread",
            category: "Sides",
            isVeg: true,
            isAvailable: true,
        },
        {
            name: "Cheesy Pasta Alfredo",
            description: "Creamy white sauce pasta with herbs",
            price: 259,
            imageUrl: "https://placehold.co/400x300/f4a261/ffffff.png?text=Pasta+Alfredo",
            category: "Sides",
            isVeg: true,
            isAvailable: true,
        },
        {
            name: "Coca-Cola (500ml)",
            description: "Chilled soft drink",
            price: 60,
            imageUrl: "https://placehold.co/400x300/1d3557/ffffff.png?text=Coca-Cola",
            category: "Beverages",
            isVeg: true,
            isAvailable: true,
        },
        {
            name: "Choco Lava Cake",
            description: "Warm chocolate cake with a molten center",
            price: 129,
            imageUrl: "https://placehold.co/400x300/6f4518/ffffff.png?text=Choco+Lava+Cake",
            category: "Desserts",
            isVeg: true,
            isAvailable: false,
        },
    ],
    time: "30-40 mins",
    costForTwo: 600,
    pickup: true,
    delivery: true,
    isOpen: true,
    rating: 4,
    ratingCount: 3521,
    code: "PH-THN-01",
    address: "Shop No. 4, Eastern Express Highway, Thane West, Mumbai, Maharashtra 400601",
    "coords": {
    "id": "1",
    "latitude": 19.1943,
    "latitudeDelta": 0.0922,
    "longitude": 72.9714,
    "longitudeDelta": 0.0421,
    "address": "Shop No. 4, Eastern Express Highway, Thane West, Mumbai, Maharashtra 400601",
    "title": "Pizza Hut"
}
};

module.exports = pizzaHutData;